// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBko6PFIC3QOZ3CXtsyN-4vrFJR2ooAeas",
    authDomain: "appmoviles-b5003.firebaseapp.com",
    projectId: "appmoviles-b5003",
    storageBucket: "appmoviles-b5003.firebasestorage.app",
    messagingSenderId: "264276022373",
    appId: "1:264276022373:web:66db567fd6ee7d225b628c",
    measurementId: "G-RXGREWNXX8"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBko6PFIC3QOZ3CXtsyN-4vrFJR2ooAeas",
    appId: "1:264276022373:android:c4a5d2cfdc85421e5b628c",
    messagingSenderId: "264276022373",
    projectId: "appmoviles-b5003",
    storageBucket: "appmoviles-b5003.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBko6PFIC3QOZ3CXtsyN-4vrFJR2ooAeas",
    appId: "1:264276022373:ios:2087b53416967ac85b628c",
    messagingSenderId: "264276022373",
    projectId: "appmoviles-b5003",
    storageBucket: "appmoviles-b5003.firebasestorage.app",
    iosBundleId: 'com.example.flutterApp2', // ajusta al bundle real si difiere
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBko6PFIC3QOZ3CXtsyN-4vrFJR2ooAeas",
    appId: "1:264276022373:ios:2087b53416967ac85b628c",
    messagingSenderId: "264276022373",
    projectId: "appmoviles-b5003",
    storageBucket: "appmoviles-b5003.firebasestorage.app",
    iosBundleId: 'com.example.flutterApp2', // ajusta al bundle real si difiere
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBko6PFIC3QOZ3CXtsyN-4vrFJR2ooAeas",
    appId: "1:264276022373:web:66db567fd6ee7d225b628c",
    messagingSenderId: "264276022373",
    projectId: "appmoviles-b5003",
    authDomain: "appmoviles-b5003.firebaseapp.com",
    storageBucket: "appmoviles-b5003.firebasestorage.app",
    measurementId: "G-RXGREWNXX8",
  );
}
