// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBko6PFIC3QOZ3CXtsyN-4vrFJR2ooAeas",
    authDomain: "appmoviles-b5003.firebaseapp.com",
    projectId: "appmoviles-b5003",
    storageBucket: "appmoviles-b5003.firebasestorage.app",
    messagingSenderId: "264276022373",
    appId: "1:264276022373:web:66db567fd6ee7d225b628c",
    measurementId: "G-RXGREWNXX8"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlGIXy7lbCKwPdrJel8xDslzEsHQRL-78',
    appId: '1:1056544919141:android:6180e6b98f708d3f68c08c',
    messagingSenderId: '1056544919141',
    projectId: 'fichamedica-app',
    storageBucket: 'fichamedica-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3fMwq5kX8gGQIv0fsCtz61rFzCkc2uKE',
    appId: '1:1056544919141:ios:65e05a01c053c22868c08c',
    messagingSenderId: '1056544919141',
    projectId: 'fichamedica-app',
    storageBucket: 'fichamedica-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3fMwq5kX8gGQIv0fsCtz61rFzCkc2uKE',
    appId: '1:1056544919141:ios:65e05a01c053c22868c08c',
    messagingSenderId: '1056544919141',
    projectId: 'fichamedica-app',
    storageBucket: 'fichamedica-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8HoDHt64Ext9nUHsJeotMiJ5P3yNIqzU',
    appId: '1:1056544919141:web:7dd92233cf9f921768c08c',
    messagingSenderId: '1056544919141',
    projectId: 'fichamedica-app',
    authDomain: 'fichamedica-app.firebaseapp.com',
    storageBucket: 'fichamedica-app.firebasestorage.app',
    measurementId: 'G-RTM9SRGVDE',
  );
}
